common_args:
  training_type: "cross_silo"
  scenario: "horizontal"
  using_mlops: false
  random_seed: 0

environment_args:
  bootstrap: config/bootstrap.sh

data_args:
  dataset: "mnist"
  data_cache_dir: "../../../../data/mnist"
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "cnn"
  model_file_cache_folder: "./model_file_cache" # will be filled by the server automatically
  global_model_file_path: "./model_file_cache/global_model.pt"

train_args:
  federated_optimizer: "FedAvg"
  privacy_optimizer: "zkp"  # "non_zkp"
  # honest_bound: 1
  norm_bound: 1.0  # also used in zkp_prob, in honest_bound
  malicious_bound: 1.0  # 1.6 or 2.4 
  check_type: "strict"  # "zkp_prob" or "normal" or "strict" or "no_check" (client bound but server no check) or "normal" (client no bound, server no check--benchmark 0.73+)
  # malicious_ratio: 0
  # chi_bound: 1
  # norm_bound: 2  # also used in zkp_prob
  ## begin for zkp_prob
  max_malicious_clients: 1
  num_blinds_per_group_element: 2
  random_normal_bit_shifter: 24
  # linear_comb_bound_bits: 44
  # max_bound_sq_bits: 100
  num_norm_bound_samples: 1000
#  standard_deviation_factor: 15.69132269
  proto_type: 'float'  # don't use 'int' (not implemented!) only use 'float'
  weight_bits: 24
  ### end for zkp_prob
  client_id_list:
  client_num_in_total: 2
  client_num_per_round: 2
  comm_round: 10
  epochs: 1
  batch_size: 64
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001

  attack_type: 'change_label' # 'noise', 'change_label', 'mp_pd', 'mp_nt'
  noise_std: 0.1 # if attack_type == 'noise'
  label_1: 5 # if attack_type is in ['change_label', 'mp_pd', 'mp_nt']
  label_2: 9 # if attack_type is in ['change_label', 'mp_pd', 'mp_nt']
  ignore_ratio: 0.01 # if attack_type == 'mp_nt'

  check_pred: 'cosine' # 'l2norm', 'sphere', 'cosine', 'zeno'
  sphere_norm_bound: 0.5 # half of norm_bound, used if check_pred == 'sphere'
  # more args if zeno

validation_args:
  frequency_of_the_test: 1

device_args:
  using_gpu: true
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_default

comm_args:
  backend: "GRPC"
  grpc_ipconfig_path: config/grpc_ipconfig.csv

tracking_args:
  # When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  local_log_output_path: ./log
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_project: fedml
  wandb_name: fedml_torch_fedavg_mnist_cnn_zkp
