# this is used for 4 clients and 1 server training within a single machine which has 8 GPUs, but you hope to skip the GPU device ID.
# mapping_default:
#     host1: [1, 1, 1, 2]
# this is used for 8 clients and 1 server training using 5 machines, each machine has 3 GPUs inside, but you hope to use the first and second GPU.
# https://github.com/FedML-AI/FedML/blob/master/python/examples/simulation/mpi_torch_fedavg_mnist_lr_example/config/gpu_mapping.yaml
mapping_default:
  10.0.0.107: [1]
  10.0.0.221: [1]
  10.0.0.153: [1]
